### ISSUE TITLE
can't access the config.yml

### ISSUE THREAD

**Issue by xiaobeilou2000** [zachowj/xfinity-data-usage#102]
Issue: after start, it complained no config file from the log

`2023-04-05 22:57:23 [error] : Config file not found.`

I am pretty sure I have the config.yml file under the source directory of the host, with proper permission, owner, group setting, etc.

I used portainer to access the console of the container but it always failed.

Here's my yaml: 

```
version: '3.7'
services:
  xfinity:
    image: zachowj/xfinity-data-usage:latest
    container_name: xfinity
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - type: bind
        source: /ssd/xfinity/config
        target: /config
    environment:
      TZ: US/Pacific
      LOGGING_LEVEL: info
    networks:
      - mynet
networks:
  mynet:
    external:
      name: mynet
```
