### ISSUE TITLE
Help using the Home Assistant endpoint

### ISSUE THREAD

**Issue by jasii** [zachowj/xfinity-data-usage#19]
Could someone please share how they are using the HA endpoint in their yaml files please.

I just get a string of JSON as the state:
`{"total_usage":543,"allowable_usage":1229,"home_usage":543,"wifi_usage":0,"courtesy_used":1,"courtesy_remaining":0,"courtesy_allowed":1,"in_paid_overage":true,"remaining_usage":686}`

My Home Assistant yaml is like this:
  - platform: rest
    name: Xfinity Internet Usage
    resource: http://192.168.1.XXX:7878/homeassistant

**Comment by zachowj** [comment]
```yaml
- platform: rest
  name: Xfinity Internet Usage
  resource: http://192.168.1.XXX:7878/homeassistant
  value_template: "{{ value_json.remaining_usage }}"
  json_attributes:
    - total_usage
    - allowable_usage
    - home_usage
    - wifi_usage
    - courtesy_used
    - courtesy_remaining
    - in_paid_coverage
```
