### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by J-CMartin** [zachowj/xfinity-data-usage#84]
How to use the latest (0.17.4) version? Docker Hub has version 0.17.1 from 1 year ago.

**Comment by zachowj** [comment]
The GitHub action that pushes the builds to docker has been/is broken. Trying to find time to fix it.

If you're using docker-compose you can always build the image directly from GitHub.

```yaml
xfinity:
    image: repo-image
    build: https://github.com/zachowj/xfinity-data-usage.git#main
    ...
```
